{% set name = "pytest-localftpserver" %}
{% set version = "1.1.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name|replace("-", "_") }}-{{ version }}.tar.gz
  sha256: 570435051df9c5f20a3ab2083b4cb7248f1af89788d514fb73c53192e9bc67d4

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.5
    - pip
  run:
    - python >=3.5
    - pyftpdlib >=1.2.0
    - pyopenssl
    - pytest

test:
  imports:
    - pytest_localftpserver
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/oz123/pytest-localftpserver
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A PyTest plugin which provides an FTP fixture for your tests
  description: |
    This Plugin provides the fixtures ftpserver and ftpserver_TLS, which are
    threaded instances of a FTP server, with which you can upload files and
    test FTP functionality.
  doc_url: https://pytest-localftpserver.readthedocs.io/en/latest/index.html
  dev_url: https://github.com/oz123/pytest-localftpserver

extra:
  recipe-maintainers:
    - leouieda
    - s-weigand
